// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnhmtdqnzfnvramxhwlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuaG10ZHFuemZudnJhbXhod2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODcwNzAsImV4cCI6MjA2ODY2MzA3MH0.uvsl6KVL7iJEyGug9QeReoxg6T9_BR1YF2B5QDF0aCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});